services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node/server
    depends_on:
      - mongo
      - postgres
    environment:
      - APP_URL=${APP_URL}
      - HOST=${HOST}
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - CONFIRM_TOKEN_SECRET=${CONFIRM_TOKEN_SECRET}
      - FORGOT_PASSWORD_TOKEN_SECRET=${FORGOT_PASSWORD_TOKEN_SECRET}
      - PASSWORD_SECRET=${PASSWORD_SECRET}
      - BREVO_API_KEY=${BREVO_API_KEY}
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/server

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - data-mongo:/data/db

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - data-postgres:/var/lib/postgresql/data

volumes:
  data-mongo:
  data-postgres:
