name: Node App CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint_frontend:
        name: Lint Frontend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./client

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'            
                cache-dependency-path: client/package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Run linting
              run:  npm run lint
    lint_backend:
        name: Lint Backend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./server

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'         
                cache-dependency-path: server/package-lock.json   

            - name: Install dependencies
              run: npm ci

            - name: Run linting
              run:  npm run lint